[package]
name = "RobloxRequests"
version = "0.1.0"
author = "Roblox"
content_root = "http"

[dependencies]
Promise = "github.com/evaera/roblox-lua-promise@3.1.0"

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@=2.3.0"
TestEZ = "github.com/roblox/jest-roblox@2.3.0"